### Extraction des codes postaux

### Listes des codes postaux

### Listes totals des codes postaux

In [1]:
import pandas as pd
import os

# Définissez le chemin du dossier contenant les fichiers Excel
dossier = "Nouveaux codes postaux"
dataframes = []

for fichier in os.listdir(dossier):
    if fichier.endswith(".xlsx"):
        chemin_fichier = os.path.join(dossier, fichier)

        dataframe = pd.read_excel(chemin_fichier)
        dataframes.append(dataframe)

# Fusionnez les DataFrames en un seul DataFrame
merged_dataframe = pd.concat(dataframes, ignore_index=True)

# Supprimez les doublons en fonction de l'index
merged_dataframe = merged_dataframe[~merged_dataframe.index.duplicated(keep='first')]

# Affichez les noms des colonnes
print("Noms des colonnes :")
print(list(merged_dataframe.columns))

# Affichez les premières lignes du DataFrame fusionné
print("Aperçu du DataFrame fusionné :")
merged_dataframe

Noms des colonnes :
['Code postal', '% dans la zone', 'Communes associées au code postal', 'Nom des communes associées au code postal', 'IRIS associés au code postal']
Aperçu du DataFrame fusionné :

,Code postal,% dans la zone,Communes associées au code postal,Nom des communes associées au code postal,IRIS associés au code postal
0,56240,66,"56014, 56029, 56089, 56104, 56166","Berné, Calan, Inguiniel, Lanvaudan, Plouay","560140000, 560290000, 560890000, 561040000, 56..."
1,56620,64,"56040, 56179","Cléguer, Pont-Scorff","560400000, 561790000"
2,56850,51,56036,Caudan,"560360101, 560360102, 560360103"
3,29300,36,"29002, 29005, 29071, 29147, 29233, 29234, 29297","Arzano, Baye, Guilligomarc'h, Mellac, Quimperl...","290020000, 290050000, 290710000, 291470000, 29..."
4,56320,11,"56057, 56105, 56131, 56182","Lanvénégen, Le Faouët, Meslan, Priziac","560570000, 561050000, 561310000, 561820000"
...,...,...,...,...,...
603,22340,23,"22128, 22137, 22157, 22163, 22202, 22344, 2235...","Le Moustoir, Locarn, Maël-Carhaix, Paule, Plév...","221280000, 221370000, 221570000, 221630000, 22..."
604,22110,21,"22061, 22087, 22146, 22220, 22229, 22266, 22365","Glomel, Kergrist-Moëlou, Mellionnec, Plouguern...","220610000, 220870000, 221460000, 222200000, 22..."
605,56340,14,"56034, 56168","Carnac, Plouharnel","560340101, 560340102, 561680000"
606,56500,10,"56017, 56039, 56117, 56140, 56141, 56144, 5617...","Bignan, La Chapelle-Neuve, Locminé, Moréac, Mo...","560170000, 560390000, 561170000, 561400000, 56..."
607,29520,6,"29027, 29122, 29249, 29267","Châteauneuf-du-Faou, Laz, Saint-Goazec, Saint-...","290270000, 291220000, 292490000, 292670000"

### Codes Uniques pour chaques minutes

In [2]:
import pandas as pd
import os

# Définissez le chemin du dossier contenant les fichiers Excel
dossier = "Nouveaux codes postaux"
dataframes = {}

# Listes pour stocker les noms des variables locales et des DataFrames
noms_variables_locales = []
noms_dataframes = []

for i, fichier in enumerate(os.listdir(dossier)):
    if fichier.endswith(".xlsx"):  
        nom_dataframe = os.path.splitext(fichier)[0].replace(" ", "_")  # Remplace les espaces par des soulignements
        chemin_fichier = os.path.join(dossier, fichier)
        
        # Chargez les données dans le DataFrame correspondant et renommez la variable locale
        nom_variable_dataframe = f"df_{nom_dataframe}"
        locals()[nom_variable_dataframe] = pd.read_excel(chemin_fichier)

        dataframes[nom_dataframe] = locals()[nom_variable_dataframe]
        
        noms_variables_locales.append(nom_variable_dataframe)
        noms_dataframes.append(nom_dataframe)

# Affichez les noms des DataFrames
print("Liste des noms de variables locales :")
print(noms_variables_locales)

Liste des noms de variables locales :
['df_15min', 'df_30min', 'df_3h', 'df_45_min']

In [3]:
df_30min

,Code postal,% dans la zone,Communes associées au code postal,Nom des communes associées au code postal,IRIS associés au code postal
0,56240,100,"56014, 56029, 56089, 56104, 56166","Berné, Calan, Inguiniel, Lanvaudan, Plouay","560140000, 560290000, 560890000, 561040000, 56..."
1,56850,100,56036,Caudan,"560360101, 560360102, 560360103"
2,56650,100,56090,Inzinzac-Lochrist,"560900101, 560900102"
3,56620,100,"56040, 56179","Cléguer, Pont-Scorff","560400000, 561790000"
4,56600,100,56098,Lanester,"560980101, 560980102, 560980103, 560980104, 56..."
5,56530,100,"56063, 56185","Gestel, Quéven","560630000, 561850101, 561850102, 561850103, 56..."
6,56100,100,56121,Lorient,"561210101, 561210102, 561210103, 561210301, 56..."
7,29300,99,"29002, 29005, 29071, 29147, 29233, 29234, 29297","Arzano, Baye, Guilligomarc'h, Mellac, Quimperl...","290020000, 290050000, 290710000, 291470000, 29..."
8,56570,98,56118,Locmiquélic,561180000
9,56320,96,"56057, 56105, 56131, 56182","Lanvénégen, Le Faouët, Meslan, Priziac","560570000, 561050000, 561310000, 561820000"
10,56260,89,56107,Larmor-Plage,"561070101, 561070102, 561070103"
11,56700,86,"56021, 56083, 56094, 56130, 56220","Brandérion, Hennebont, Kervignac, Merlevenez, ...","560210000, 560830101, 560830102, 560830103, 56..."
12,56540,73,"56048, 56210, 56238, 56264","Kernascléden, Le Croisty, Saint-Caradec-Trégom...","560480000, 562100000, 562380000, 562640000"
13,56670,72,56193,Riantec,561930000
14,56520,71,56078,Guidel,"560780101, 560780102, 560780103, 560780104"
15,29310,56,"29136, 29230","Locunolé, Querrien","291360000, 292300000"
16,29360,47,29031,Clohars-Carnoët,290310000
17,56440,45,56101,Languidic,"561010101, 561010102, 561010103"
18,56270,43,56162,Ploemeur,"561620101, 561620102, 561620103, 561620104, 56..."
19,56310,42,"56026, 56076, 56128, 56173, 56188","Bubry, Guern, Melrand, Pluméliau-Bieuzy, Quist...","560260000, 560760000, 561280000, 561730000, 56..."
20,56160,37,"56073, 56099, 56110, 56113, 56156, 56163, 56242","Guémené-sur-Scorff, Langoëlan, Lignol, Locmalo...","560730000, 560990000, 561100000, 561130000, 56..."
21,56630,26,56100,Langonnet,561000000
22,29350,24,29150,Moëlan-sur-Mer,"291500101, 291500102, 291500103"
23,56110,17,"56066, 56199, 56201","Gourin, Le Saint, Roudouallec","560660000, 561990000, 562010000"
24,56560,13,56081,Guiscriff,560810000
25,56680,11,"56062, 56169","Gâvres, Plouhinec","560620000, 561690000"
26,56690,11,"56096, 56097, 56148","Landaul, Landévant, Nostang","560960000, 560970000, 561480000"
27,29340,11,29236,Riec-sur-Bélon,292360000
28,29380,9,"29004, 29269, 29300","Bannalec, Le Trévoux, Saint-Thurien","290040000, 292690000, 293000000"
29,56290,6,56181,Port-Louis,561810000

In [4]:
import pandas as pd
codes_postaux = df_15min['Code postal'].tolist()
df_30min = df_30min[~df_30min['Code postal'].isin(codes_postaux)]

In [5]:
df_30min

,Code postal,% dans la zone,Communes associées au code postal,Nom des communes associées au code postal,IRIS associés au code postal
4,56600,100,56098,Lanester,"560980101, 560980102, 560980103, 560980104, 56..."
5,56530,100,"56063, 56185","Gestel, Quéven","560630000, 561850101, 561850102, 561850103, 56..."
6,56100,100,56121,Lorient,"561210101, 561210102, 561210103, 561210301, 56..."
8,56570,98,56118,Locmiquélic,561180000
10,56260,89,56107,Larmor-Plage,"561070101, 561070102, 561070103"
11,56700,86,"56021, 56083, 56094, 56130, 56220","Brandérion, Hennebont, Kervignac, Merlevenez, ...","560210000, 560830101, 560830102, 560830103, 56..."
12,56540,73,"56048, 56210, 56238, 56264","Kernascléden, Le Croisty, Saint-Caradec-Trégom...","560480000, 562100000, 562380000, 562640000"
13,56670,72,56193,Riantec,561930000
14,56520,71,56078,Guidel,"560780101, 560780102, 560780103, 560780104"
15,29310,56,"29136, 29230","Locunolé, Querrien","291360000, 292300000"
16,29360,47,29031,Clohars-Carnoët,290310000
17,56440,45,56101,Languidic,"561010101, 561010102, 561010103"
18,56270,43,56162,Ploemeur,"561620101, 561620102, 561620103, 561620104, 56..."
19,56310,42,"56026, 56076, 56128, 56173, 56188","Bubry, Guern, Melrand, Pluméliau-Bieuzy, Quist...","560260000, 560760000, 561280000, 561730000, 56..."
20,56160,37,"56073, 56099, 56110, 56113, 56156, 56163, 56242","Guémené-sur-Scorff, Langoëlan, Lignol, Locmalo...","560730000, 560990000, 561100000, 561130000, 56..."
21,56630,26,56100,Langonnet,561000000
22,29350,24,29150,Moëlan-sur-Mer,"291500101, 291500102, 291500103"
23,56110,17,"56066, 56199, 56201","Gourin, Le Saint, Roudouallec","560660000, 561990000, 562010000"
24,56560,13,56081,Guiscriff,560810000
25,56680,11,"56062, 56169","Gâvres, Plouhinec","560620000, 561690000"
26,56690,11,"56096, 56097, 56148","Landaul, Landévant, Nostang","560960000, 560970000, 561480000"
27,29340,11,29236,Riec-sur-Bélon,292360000
28,29380,9,"29004, 29269, 29300","Bannalec, Le Trévoux, Saint-Thurien","290040000, 292690000, 293000000"
29,56290,6,56181,Port-Louis,561810000

### Recherche dans la base de données

In [5]:
import psycopg2
import pandas as pd

# Récupérez les codes postaux du DataFrame
codes_postaux = df_3h["Code postal"].tolist()

# Convertissez les codes postaux en chaînes de caractères (str)
codes_postaux_str = [str(code_postal) for code_postal in codes_postaux]

# Établissez la connexion à votre base de données PostgreSQL
conn = psycopg2.connect(
    host="localhost",
    database="Base",
    user="waouhmonde",
    password="waouhmonde"
)

# Créez une requête SQL pour rechercher les lignes correspondantes dans votre table
query = "SELECT * FROM ma_table WHERE code_postal IN %s"

# Exécutez la requête SQL en utilisant les codes postaux convertis comme paramètres
df = pd.read_sql_query(query, conn, params=(tuple(codes_postaux_str),))

# Fermez la connexion à la base de données
conn.close()

# Affichez le DataFrame résultant
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_14940\12109728.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn, params=(tuple(codes_postaux_str),))

Empty DataFrame
Columns: [id, nom, adresse, code_postal, ville, numero_telephone, tranche_age, autre_colonne]
Index: []

In [153]:
df

,id,nom,adresse,code_postal,ville,numero_telephone,tranche_age,autre_colonne
0,250501,Paula Santiago,PL MAIL,26230,GRIGNAN,475465691,ENTRE 30 ET 50 ANS,2
1,206279,Agnès Mejean,QUART COURCOUSONE,26780,ALLAN,475522287,ENTRE 50 ET 70 ANS,1
2,206377,Fata Valérie La,QUART SASTRE CHE MONCEAU,26780,ALLAN,475905251,+ 70 Ans,1
3,206378,Florence Chabanis,QUART MÉGE,26780,ALLAN,475964762,ENTRE 30 ET 50 ANS,2
4,206379,Florian Chabaud,1410 RTE AIGUEBELLE,26780,ALLAN,475466841,ENTRE 18 ET 30 ANS,1
...,...,...,...,...,...,...,...,...
31098,364124,Michel Dollet,LE PLAN,26560,VERS SUR MÉOUGE,475285134,ENTRE 50 ET 70 ANS,2
31099,364225,Yvette Brunel,QUART LASSAGNE,26560,VILLEFRANCHE LE CHÂTEAU,475285420,ENTRE 50 ET 70 ANS,2
31100,364125,Patrick Berato,LE PRÉ ROND,26560,VERS SUR MÉOUGE,475275627,ENTRE 50 ET 70 ANS,2
31101,364126,Philippe Mousseau,QUART VOLUY,26560,VERS SUR MEOUGE,475264463,ENTRE 50 ET 70 ANS,2
31102,364127,Raymond Raspail,QUART VOLUY,26560,VERS SUR MEOUGE,475285162,ENTRE 50 ET 70 ANS,2

In [7]:
df_3h

,Code postal,% dans la zone,Communes associées au code postal,Nom des communes associées au code postal,IRIS associés au code postal
0,85710,100,"85024, 85062, 85096","Bois-de-Céné, Châteauneuf, La Garnache","850240000, 850620000, 850960000"
1,22000,100,22278,Saint-Brieuc,"222780101, 222780102, 222780103, 222780104, 22..."
2,22100,100,"22003, 22008, 22021, 22026, 22050, 22082, 2211...","Aucaleuc, Bobital, Brusvily, Calorguen, Dinan,...","220030000, 220080000, 220210000, 220260000, 22..."
4,22120,100,"22081, 22246, 22258, 22389","Hillion, Pommeret, Quessoy, Yffiniac","220810000, 222460000, 222580000, 223890000"
5,22130,100,"22014, 22048, 22049, 22096, 22105, 22172, 2220...","Bourseul, Corseul, Créhen, Landébia, Languenan...","220140000, 220480000, 220490000, 220960000, 22..."
...,...,...,...,...,...
514,14380,12,"14054, 14352, 14424, 14511, 14559, 14619, 14658","Beaumesnil, Landelles-et-Coupigny, Le Mesnil-R...","140540000, 143520000, 144240000, 145110000, 14..."
515,50510,9,"50109, 50120, 50252, 50278, 50304, 50327, 50549","Chanteloup, Cérences, Hudimesnil, La Meurdraqu...","501090000, 501200000, 502520000, 502780000, 50..."
516,53340,7,"53017, 53019, 53067, 53076, 53184, 53257","Bannes, Chémeré-le-Roi, Cossé-en-Champagne, Pr...","530170000, 530190000, 530670000, 530760000, 53..."
517,49330,6,"49080, 49132, 49170, 49205, 49330","Juvardeil, Les Hauts-d'Anjou, Miré, Sceaux-d'A...","490800000, 491320000, 491700000, 492050000, 49..."
518,85190,6,"85003, 85016, 85098, 85130, 85300","Aizenay, Beaulieu-sous-la-Roche, La Genétouze,...","850030101, 850030102, 850160000, 850980000, 85..."

### Recherches des codes postaux dans un fichiers Excels

In [6]:
import pandas as pd
# Remplacez 'nom_du_fichier.xlsx' par le nom de votre fichier Excel
nom_du_fichier = 'Bases_envoyees.xlsx'
# Utilisez la fonction read_excel pour lire le fichier Excel
df = pd.read_excel(nom_du_fichier)
df

,nom,prenom,adresse,cp,ville,tel,AUTORISE BLOCTEL
0,LAURENCE,RENARD,46 RUE PASTEUR,29140,ROSPORDEN,222127963,2023-10-27
1,TOURET,SEBASTIEN,13 RUE YVES KERGUELEN,56400,AURAY,290981528,2023-10-27
2,LEBRETON,JACQUES,21 RUE ETANG,56700,KERVIGNAC,952584898,2023-10-27
3,COADIC ROLAND,LE,10 RUE DES ORTANCIAS,22340,PAULE,296298674,2023-10-27
4,HUDSON,JOHN,8 RUE CHATEAUNEUF,29520,SAINT THOIS,222255952,2023-10-27
...,...,...,...,...,...,...,...
284131,KERNEN,AMBROISINE,RUE DU MAREGO,56440,LANGUIDIC,297652368,2023-10-27
284132,GOFF JULIEN,LE,19 RUE JULES FERRY,56600,LANESTER,953578304,2023-10-27
284133,MARTIN,PHILLIPPE-JEAN,5 RUE ECHELLES,56700,HENNEBONT,290612262,2023-10-27
284134,NAVELLOU,FREDERIC,LIEU-DIT KERRAIGN,29390,LEUHAN,256048904,2023-10-27
284135,SCAVINER,PATRICE,25 CITE PINS,29350,MOELAN SUR MER,298397440,2023-10-27

In [8]:
# Supposons que vous avez deux DataFrames df1 et df2

# Récupérez les codes postaux de df1 dans une liste
codes_postaux_df1 = df_3h['Code postal'].tolist()

# Créez une liste de lignes de df où le code postal est dans la liste de codes postaux de df1
resultats = df[df['cp'].isin(codes_postaux_df1)]

In [9]:
resultats

,nom,prenom,adresse,cp,ville,tel,AUTORISE BLOCTEL
16,HORROBIN,STELLA,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,2023-10-27
19,GALLUDEC CHRISTIAN,LE,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,2023-10-27
34,VANDESBOSCH,FRANCK,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,2023-10-27
38,ANNE,THOMAZIC,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,2023-10-27
78,LE,SAUX MARCEL,11 LANGOLEN,29370,CORAY,298591404,2023-10-27
...,...,...,...,...,...,...,...
283946,PABOEUF,ERIC,8 RUE ST GILLES,29370,ELLIANT,222124744,2023-10-27
283960,LE,NEZET ELODIE,NaN,56920,NOYAL PONTIVY,980749298,2023-10-27
284048,MICHELLE LE,DENMAT,6 RUE STE TREPHINE,22570,LANISCAT,662057458,2023-10-27
284091,LINDA,CAIRO,NaN,56390,LOCQUELTAS,681367127,2023-10-27
284102,HUOT,PIERRE,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,2023-10-27

In [ ]:
import pandas as pd

# Supposons que vous ayez un DataFrame appelé df que vous souhaitez enregistrer dans un fichier Excel
# Spécifiez le nom du fichier Excel dans lequel vous souhaitez enregistrer le DataFrame
nom_fichier_excel = '3h.xlsx'

# Utilisez la méthode to_excel pour enregistrer le DataFrame dans le fichier Excel
resultats.to_excel(nom_fichier_excel, index=False)  # L'argument index=False évite d'enregistrer l'index du DataFrame

print(f"Le DataFrame a été enregistré dans {nom_fichier_excel}")

,Prénoms,Complément d'adresse,Distance de l'enseigne,Adresse mail,N° Mobile,N° Fixe,Date 1 à proposer,Date 2 à proposer,Date 3 à proposer,Date 4 à proposer,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
0,Menu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rechercher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Rechercher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Se,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Outils,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2244,Foundation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2245,Inc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2246,Unis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2247,Politique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2248,Version,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Transformation et ajout de colonnes

In [123]:
### Ajout de colonnes

In [10]:
resultats

,nom,prenom,adresse,cp,ville,tel,AUTORISE BLOCTEL
16,HORROBIN,STELLA,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,2023-10-27
19,GALLUDEC CHRISTIAN,LE,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,2023-10-27
34,VANDESBOSCH,FRANCK,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,2023-10-27
38,ANNE,THOMAZIC,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,2023-10-27
78,LE,SAUX MARCEL,11 LANGOLEN,29370,CORAY,298591404,2023-10-27
...,...,...,...,...,...,...,...
283946,PABOEUF,ERIC,8 RUE ST GILLES,29370,ELLIANT,222124744,2023-10-27
283960,LE,NEZET ELODIE,NaN,56920,NOYAL PONTIVY,980749298,2023-10-27
284048,MICHELLE LE,DENMAT,6 RUE STE TREPHINE,22570,LANISCAT,662057458,2023-10-27
284091,LINDA,CAIRO,NaN,56390,LOCQUELTAS,681367127,2023-10-27
284102,HUOT,PIERRE,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,2023-10-27

In [11]:
import pandas as pd

# Liste des noms de colonnes à ajouter
noms_des_colonnes = [
    'Complément d\'adresse',
    'Distance de l\'enseigne',
    'Adresse mail', 'N° Mobile', 'N° Fixe',
    'Date 1 à proposer', 'Date 2 à proposer', 'Date 3 à proposer', 'Date 4 à proposer',
    'Nom de l\'animateur enseigne', 'Nom de l\'enseigne', 'Numéro téléphone de l\'enseigne',
    'Adresse libellé voie de l\'enseigne', 'Complément d\'adresse de l\'enseigne',
    'Code postal de l\'enseigne', 'Ville de l\'enseigne', 'Numéro de l\'enseigne',
    'Infoloc enseigne', 'Code CP INSEE', 'Cadeau 1', 'Cadeau 2', 'Cadeau 3', 'Cadeau 4',
    'Date de la dernière invitation', 'Date de naissance Conjoint 1', 'Date de naissance Conjoint 2',
    'Type d\'occupant', 'Type d\'habitation', 'Commentaires'
]

# Créez un DataFrame vide avec les noms de colonnes
colonnes_vides = pd.DataFrame(columns=noms_des_colonnes)

# Ajoutez les colonnes vides à df
df = pd.concat([resultats, colonnes_vides], axis=1)

In [12]:
df

,nom,prenom,adresse,cp,ville,tel,AUTORISE BLOCTEL,Complément d'adresse,Distance de l'enseigne,Adresse mail,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
16,HORROBIN,STELLA,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,GALLUDEC CHRISTIAN,LE,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,VANDESBOSCH,FRANCK,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,ANNE,THOMAZIC,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,LE,SAUX MARCEL,11 LANGOLEN,29370,CORAY,298591404,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283946,PABOEUF,ERIC,8 RUE ST GILLES,29370,ELLIANT,222124744,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283960,LE,NEZET ELODIE,NaN,56920,NOYAL PONTIVY,980749298,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284048,MICHELLE LE,DENMAT,6 RUE STE TREPHINE,22570,LANISCAT,662057458,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284091,LINDA,CAIRO,NaN,56390,LOCQUELTAS,681367127,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284102,HUOT,PIERRE,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,2023-10-27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
import pandas as pd
# Définissez les valeurs spécifiques pour les colonnes "Nom de l'enseigne", "Adresse libellé voie de l'enseigne", "Code postal de l'enseigne", "Ville de l'enseigne" et "Numéro de l'enseigne"
nom_enseigne = "LE MONDE DE LUCIEN"
adresse_enseigne = "10, rue René LAENNEC"
code_postal_enseigne = "56240"
ville_enseigne = "PLOUAY"
numero_enseigne = "02 70 18 30 00"
Cadeau_1 = "1 ensemble de couteaux de chef"
Cadeau_2 = "1 délicieuse bouteille de vin"
Cadeau_3 = "1 bracelet monté d'un élément SWAROSKI"
Cadeau_4 = "1 Box séjours pour plusieurs destinations de choix"

# Créez une série pandas avec les valeurs spécifiques
valeurs_specifiques = pd.Series({
    "Nom de l'enseigne": nom_enseigne,
    "Adresse libellé voie de l'enseigne": adresse_enseigne,
    "Code postal de l'enseigne": code_postal_enseigne,
    "Ville de l'enseigne": ville_enseigne,
    "Numéro de l'enseigne": numero_enseigne,
    "Cadeau 1": Cadeau_1,
    "Cadeau 2": Cadeau_2,
    "Cadeau 3": Cadeau_3,
    "Cadeau 4": Cadeau_4
})

# Remplissez toutes les lignes du DataFrame avec les mêmes valeurs spécifiques
df = df.fillna(valeurs_specifiques)

# Toutes les lignes de df ont maintenant les mêmes valeurs pour les colonnes spécifiées

In [14]:
df

,nom,prenom,adresse,cp,ville,tel,AUTORISE BLOCTEL,Complément d'adresse,Distance de l'enseigne,Adresse mail,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
16,HORROBIN,STELLA,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
19,GALLUDEC CHRISTIAN,LE,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
34,VANDESBOSCH,FRANCK,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
38,ANNE,THOMAZIC,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
78,LE,SAUX MARCEL,11 LANGOLEN,29370,CORAY,298591404,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283946,PABOEUF,ERIC,8 RUE ST GILLES,29370,ELLIANT,222124744,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283960,LE,NEZET ELODIE,NaN,56920,NOYAL PONTIVY,980749298,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284048,MICHELLE LE,DENMAT,6 RUE STE TREPHINE,22570,LANISCAT,662057458,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284091,LINDA,CAIRO,NaN,56390,LOCQUELTAS,681367127,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284102,HUOT,PIERRE,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,2023-10-27,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN

In [124]:
### Suprimer une colonnes

In [15]:
import pandas as pd

# Supprimer la colonne "Nom" par exemple
nom_colonne_a_supprimer = "AUTORISE BLOCTEL"
df = df.drop(nom_colonne_a_supprimer, axis=1)

### Suprimer les noms arrabes

In [5]:
import pandas as pd
# Remplacez 'nom_du_fichier.xlsx' par le nom de votre fichier Excel
nom_du_fichier = 'KSM-PLOUAY 30 min S47 23.xlsx'
# Utilisez la fonction read_excel pour lire le fichier Excel
df = pd.read_excel(nom_du_fichier)

In [16]:
df

,nom,prenom,adresse,cp,ville,tel,Complément d'adresse,Distance de l'enseigne,Adresse mail,N° Mobile,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
16,HORROBIN,STELLA,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
19,GALLUDEC CHRISTIAN,LE,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
34,VANDESBOSCH,FRANCK,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
38,ANNE,THOMAZIC,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
78,LE,SAUX MARCEL,11 LANGOLEN,29370,CORAY,298591404,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283946,PABOEUF,ERIC,8 RUE ST GILLES,29370,ELLIANT,222124744,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283960,LE,NEZET ELODIE,NaN,56920,NOYAL PONTIVY,980749298,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284048,MICHELLE LE,DENMAT,6 RUE STE TREPHINE,22570,LANISCAT,662057458,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284091,LINDA,CAIRO,NaN,56390,LOCQUELTAS,681367127,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284102,HUOT,PIERRE,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df

,nom,prenom,adresse,cp,ville,tel,Complément d'adresse,Distance de l'enseigne,Adresse mail,N° Mobile,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
16,HORROBIN,STELLA,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
19,GALLUDEC CHRISTIAN,LE,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
34,VANDESBOSCH,FRANCK,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
38,ANNE,THOMAZIC,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
78,LE,SAUX MARCEL,11 LANGOLEN,29370,CORAY,298591404,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283946,PABOEUF,ERIC,8 RUE ST GILLES,29370,ELLIANT,222124744,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283960,LE,NEZET ELODIE,NaN,56920,NOYAL PONTIVY,980749298,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284048,MICHELLE LE,DENMAT,6 RUE STE TREPHINE,22570,LANISCAT,662057458,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284091,LINDA,CAIRO,NaN,56390,LOCQUELTAS,681367127,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284102,HUOT,PIERRE,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
import pandas as pd

# Lire le fichier Excel dans df1
nom_du_fichier = 'prenoms_arabes.xlsx'
df1 = pd.read_excel(nom_du_fichier)

prénoms_arabes = df1['Prénoms']

masque = df['prenom'].isin(prénoms_arabes)
df = df[~masque]

In [20]:
df

,nom,prenom,adresse,cp,ville,tel,Complément d'adresse,Distance de l'enseigne,Adresse mail,N° Mobile,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
16,HORROBIN,STELLA,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
19,GALLUDEC CHRISTIAN,LE,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
34,VANDESBOSCH,FRANCK,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
38,ANNE,THOMAZIC,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
78,LE,SAUX MARCEL,11 LANGOLEN,29370,CORAY,298591404,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283946,PABOEUF,ERIC,8 RUE ST GILLES,29370,ELLIANT,222124744,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283960,LE,NEZET ELODIE,NaN,56920,NOYAL PONTIVY,980749298,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284048,MICHELLE LE,DENMAT,6 RUE STE TREPHINE,22570,LANISCAT,662057458,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284091,LINDA,CAIRO,NaN,56390,LOCQUELTAS,681367127,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284102,HUOT,PIERRE,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.pop("prenom")
df

,nom,adresse,cp,ville,tel,Complément d'adresse,Distance de l'enseigne,Adresse mail,N° Mobile,N° Fixe,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
16,HORROBIN,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
19,GALLUDEC CHRISTIAN,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
34,VANDESBOSCH,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
38,ANNE,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
78,LE,11 LANGOLEN,29370,CORAY,298591404,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283946,PABOEUF,8 RUE ST GILLES,29370,ELLIANT,222124744,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283960,LE,NaN,56920,NOYAL PONTIVY,980749298,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284048,MICHELLE LE,6 RUE STE TREPHINE,22570,LANISCAT,662057458,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284091,LINDA,NaN,56390,LOCQUELTAS,681367127,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284102,HUOT,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df

,nom,adresse,cp,ville,tel,Complément d'adresse,Distance de l'enseigne,Adresse mail,N° Mobile,N° Fixe,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
16,HORROBIN,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
19,GALLUDEC CHRISTIAN,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
34,VANDESBOSCH,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
38,ANNE,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
78,LE,11 LANGOLEN,29370,CORAY,298591404,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283946,PABOEUF,8 RUE ST GILLES,29370,ELLIANT,222124744,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283960,LE,NaN,56920,NOYAL PONTIVY,980749298,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284048,MICHELLE LE,6 RUE STE TREPHINE,22570,LANISCAT,662057458,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284091,LINDA,NaN,56390,LOCQUELTAS,681367127,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284102,HUOT,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN

### Formatage du numéro de téléphone ou Fixe

In [23]:
df

,nom,adresse,cp,ville,tel,Complément d'adresse,Distance de l'enseigne,Adresse mail,N° Mobile,N° Fixe,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
16,HORROBIN,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
19,GALLUDEC CHRISTIAN,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
34,VANDESBOSCH,LIEU-DIT LUZERN,56390,GRAND CHAMP,953247931,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
38,ANNE,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
78,LE,11 LANGOLEN,29370,CORAY,298591404,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283946,PABOEUF,8 RUE ST GILLES,29370,ELLIANT,222124744,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283960,LE,NaN,56920,NOYAL PONTIVY,980749298,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284048,MICHELLE LE,6 RUE STE TREPHINE,22570,LANISCAT,662057458,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284091,LINDA,NaN,56390,LOCQUELTAS,681367127,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284102,HUOT,369 LIEU-DIT TALBOT,56390,GRAND CHAMP,952242257,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
tel

In [31]:
import re
import pandas as pd

def est_mobile(numero):
    motif_mobile = r'^(6\d{8}|\+336\d{8}|6\d{7}|\+336\d{7}|[1-5]\d{8]|[1-5]\.\d{2}\.\d{2}\.\d{2])'
    return bool(re.match(motif_mobile, str(numero)))  # Convertir en chaîne de caractères

def est_fixe(numero):
    # Motif pour les numéros de téléphone fixe avec 9 chiffres
    motif_fixe = r'^(0[1-5]\d{7}|0[8-9]\d{7}|[1-5]\d{7}|[6-9]\d{7])'
    return bool(re.match(motif_fixe, str(numero)))  # Convertir en chaîne de caractères

df_fixe = df[df['tel'].apply(est_fixe)].copy()

# Supprimer la colonne "N° Fixe" si elle existe déjà
if 'N° Fixe' in df_fixe.columns:
    df_fixe.drop(columns=['N° Fixe'], inplace=True)

# Renommer la colonne "N° Mobile" en "N° Fixe"
df_fixe.rename(columns={'tel': 'N° Fixe'}, inplace=True)
df_fixe.rename(columns={'N° Mobile': 'N° Mobile fiabilise'}, inplace=True)
df_fixe.rename(columns={'cp': 'Code postal'}, inplace=True)

# Créer un DataFrame pour les numéros de téléphone mobile
df_mobile = df[df['tel'].apply(est_mobile)].copy()
df_mobile.rename(columns={'N° Mobile': 'N° Mobile fiabilise'}, inplace=True)
df_mobile.rename(columns={'tel': 'N° Mobile'}, inplace=True)
df_mobile.rename(columns={'cp': 'Code postal'}, inplace=True)

In [32]:
df_fixe

,nom,adresse,Code postal,ville,N° Fixe,Complément d'adresse,Distance de l'enseigne,Adresse mail,N° Mobile fiabilise,Date 1 à proposer,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
16,HORROBIN,LIEU-DIT KERGALL,22570,LESCOUET GOUAREC,296366956,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
19,GALLUDEC CHRISTIAN,RUE DES 4 FRERES JACOB,56390,GRAND-CHAMP,297664293,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
38,ANNE,33 HAMEAU DU LOCH,56390,LOCQUELTAS,297666249,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
78,LE,11 LANGOLEN,29370,CORAY,298591404,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
136,NADINE,ZONE ARTISANALE DE KERYANNIC,29370,ELLIANT,298941068,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283872,LE,5 RUE LA FONTAINE,56920,SAINT GONNERY,297384345,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283880,CELINA,7 RUE DES FAUVETTES,56390,LOCMARIA-GRAND-CHAMP,297632239,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283892,LE,GOAFFRE,56920,GUELTAS,297389256,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283894,R,NaN,56920,KERFOURN,297383625,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
283946,PABOEUF,8 RUE ST GILLES,29370,ELLIANT,222124744,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df_mobile

,nom,adresse,Code postal,ville,N° Mobile,Complément d'adresse,Distance de l'enseigne,Adresse mail,N° Mobile fiabilise,N° Fixe,...,Cadeau 1,Cadeau 2,Cadeau 3,Cadeau 4,Date de la dernière invitation,Date de naissance Conjoint 1,Date de naissance Conjoint 2,Type d'occupant,Type d'habitation,Commentaires
2994,CADORET,28 ROUTE DE PLUMERGAT,56390,GRAND CHAMP,611881321,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
3875,MOELLIC,14 RUE DES NOISETIERS,56390,COLPO,678812434,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
4171,SINQUIN,2 A RUE TACHEN FOIRE,29370,CORAY,643004923,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
4792,YVETTE,56 AVENUE DE LA PRINCESSE,56390,COLPO,660314645,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
4942,RAMILLON,11 RUE MAX JACOB,29370,ELLIANT,645276791,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281414,LIONEL,LIEU-DIT KERMENESY,56390,LOCMARIA GRAND CHAMP,626162632,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
281845,ARNAUD,LIEU-DIT GUENFROUT,56390,GRAND CHAMP,673734744,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
282896,THIERRY,7 RUE PONTORSON,56920,NOYAL PONTIVY,684997123,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284048,MICHELLE LE,6 RUE STE TREPHINE,22570,LANISCAT,662057458,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN
284091,LINDA,NaN,56390,LOCQUELTAS,681367127,NaN,NaN,NaN,NaN,NaN,...,1 ensemble de couteaux de chef,1 délicieuse bouteille de vin,1 bracelet monté d'un élément SWAROSKI,1 Box séjours pour plusieurs destinations de c...,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df00 = df_fixe

In [36]:
df00 = df_mobile

In [35]:
import pandas as pd
import os

# Remplacez 'nom_du_fichier_original.xlsx' par le chemin de votre fichier Excel d'origine
#fichier_original = 'KSM-PLOUAY 3heures.xlsx'

# Remplacez 'chemin_dossier_destination' par le chemin du dossier où vous souhaitez enregistrer les fichiers
dossier_destination = 'Fiches Moins de 3Mo'

# Assurez-vous que le dossier de destination existe, sinon, créez-le
if not os.path.exists(dossier_destination):
    os.makedirs(dossier_destination)

# Charger le fichier Excel d'origine en tant que DataFrame
#df_original = pd.read_excel(fichier_original)

# Initialisez un compteur de partie
partie = 1
chunk_size = 50000  # Nombre de lignes dans chaque morceau

# Tant qu'il y a plus de lignes restantes dans le DataFrame
while not df00.empty:
    # Sélectionnez les premières lignes (un morceau)
    df_partie = df00.head(chunk_size)
    
    # Enregistrez la partie dans un fichier Excel dans le dossier de destination
    nom_fichier_partie = os.path.join(dossier_destination, f'partie{partie}.xlsx')
    df_partie.to_excel(nom_fichier_partie, index=False)
    
    # Supprimez les lignes extraites du DataFrame d'origine
    df00 = df00.iloc[chunk_size:]
    
    # Incrémentez le compteur de partie
    partie += 1

print(f"Fichiers créés avec succès dans le dossier de destination : {dossier_destination}")

Fichiers créés avec succès dans le dossier de destination : Fiches Moins de 3Mo

In [37]:
import pandas as pd
import os

# Remplacez 'nom_du_fichier_original.xlsx' par le chemin de votre fichier Excel d'origine
#fichier_original = 'KSM-PLOUAY 3heures.xlsx'

# Remplacez 'chemin_dossier_destination' par le chemin du dossier où vous souhaitez enregistrer les fichiers
dossier_destination = 'Fiches Moins de 3Mo'

# Assurez-vous que le dossier de destination existe, sinon, créez-le
if not os.path.exists(dossier_destination):
    os.makedirs(dossier_destination)

# Charger le fichier Excel d'origine en tant que DataFrame
#df_original = pd.read_excel(fichier_original)

# Initialisez un compteur de partie
partie = 1
chunk_size = 50000  # Nombre de lignes dans chaque morceau

# Tant qu'il y a plus de lignes restantes dans le DataFrame
while not df00.empty:
    # Sélectionnez les premières lignes (un morceau)
    df_partie = df00.head(chunk_size)
    
    # Enregistrez la partie dans un fichier Excel dans le dossier de destination
    nom_fichier_partie = os.path.join(dossier_destination, f'partie0{partie}.xlsx')
    df_partie.to_excel(nom_fichier_partie, index=False)
    
    # Supprimez les lignes extraites du DataFrame d'origine
    df00 = df00.iloc[chunk_size:]
    
    # Incrémentez le compteur de partie
    partie += 1

print(f"Fichiers créés avec succès dans le dossier de destination : {dossier_destination}")

Fichiers créés avec succès dans le dossier de destination : Fiches Moins de 3Mo